### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by ziadsarour** [mixpanel/mixpanel-flutter#151]
It happened in iOS and Android

```
environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.22.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  app_badge_plus: 1.1.2
  auto_size_text: 3.0.0
  clock: 1.1.1
  cupertino_icons: 1.0.8
  device_info_plus: 10.1.0
  dotted_border: 2.1.0
  expandable_page_view: 1.0.17
  extended_image: 8.2.1
  faker: 2.1.0
  feedback: 3.1.0
  fl_chart: 0.68.0
  flutter_image_compress: 2.3.0
  flutter_local_notifications: 17.2.1+2
  flutter_native_splash: 2.4.1
  flutter_spinkit: 5.2.1
  flutter_svg: 2.0.10+1
  flutter_timezone: 2.1.0
  flutter_volume_controller: 1.3.2
  flutter_widget_from_html_core: 0.15.1
  get_it: 7.7.0
  html: 0.15.4
  http: 1.2.2
  image_picker: 1.1.2
  in_app_review: 2.0.9
  infinite_scroll_pagination: 4.0.0
  intl: 0.19.0
  jiffy: 6.3.1
  logging: 1.2.0
  lottie: 3.1.2
  mixpanel_flutter: 2.3.1
  mobile_scanner: 5.0.2
  modal_bottom_sheet: 3.0.0
  objectbox: 4.0.1
  objectbox_flutter_libs: 4.0.1
  package_info_plus: 8.0.0
  path_provider: 2.1.3
  permission_handler: 11.3.1
  pretty_qr_code: 3.3.0
  purchases_flutter: 6.30.2
  share_plus: 9.0.0
  shimmer: 3.0.0
  slang: 3.31.1
  slang_flutter: 3.31.0
  sprung: 3.0.1
  timezone: 0.9.4
  toastification: 2.1.0
  url_launcher: 6.3.0
  uuid: 4.4.2

  # Firebase dependencies
  cloud_firestore: 5.1.0
  cloud_functions: 5.0.3
  firebase_analytics: 11.2.0
  firebase_core: 3.2.0
  firebase_crashlytics: 4.0.3
  firebase_dynamic_links: 6.0.3
  firebase_messaging: 15.0.3
  firebase_performance: 0.10.0+3
  firebase_remote_config: 5.0.3
  firebase_storage: 12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: 2.4.11
  fake_async: 1.3.1
  flutter_lints: 4.0.0
  icons_launcher: 2.1.7
  mockito: 5.4.4
  objectbox_generator: 4.0.1
  patrol: 3.9.0
  slang_gpt: 0.10.2

dependency_overrides:
  js: 0.7.1
```

```
E/MethodChannel#mixpanel_flutter(29412): Failed to handle method call
E/MethodChannel#mixpanel_flutter(29412): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#mixpanel_flutter(29412): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E/MethodChannel#mixpanel_flutter(29412): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:272)
E/MethodChannel#mixpanel_flutter(29412): 	at com.mixpanel.mixpanel_flutter.MixpanelFlutterPlugin.handleIdentify(MixpanelFlutterPlugin.java:257)
E/MethodChannel#mixpanel_flutter(29412): 	at com.mixpanel.mixpanel_flutter.MixpanelFlutterPlugin.onMethodCall(MixpanelFlutterPlugin.java:80)
E/MethodChannel#mixpanel_flutter(29412): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#mixpanel_flutter(29412): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#mixpanel_flutter(29412): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#mixpanel_flutter(29412): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#mixpanel_flutter(29412): 	at android.os.Handler.handleCallback(Handler.java:883)
E/MethodChannel#mixpanel_flutter(29412): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/MethodChannel#mixpanel_flutter(29412): 	at android.os.Looper.loop(Looper.java:237)
E/MethodChannel#mixpanel_flutter(29412): 	at android.app.ActivityThread.main(ActivityThread.java:7948)
E/MethodChannel#mixpanel_flutter(29412): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#mixpanel_flutter(29412): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#mixpanel_flutter(29412): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/DartMessenger(29412): Uncaught exception in binary message listener
E/DartMessenger(29412): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(29412): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E/DartMessenger(29412): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:287)
E/DartMessenger(29412): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/DartMessenger(29412): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/DartMessenger(29412): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(29412): 	at android.os.Handler.handleCallback(Handler.java:883)
E/DartMessenger(29412): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/DartMessenger(29412): 	at android.os.Looper.loop(Looper.java:237)
E/DartMessenger(29412): 	at android.app.ActivityThread.main(ActivityThread.java:7948)
E/DartMessenger(29412): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(29412): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/DartMessenger(29412): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```
